Repository festal-kestrel/wedding-book-keeper-be, pull requests merged in 2023-06, with the labels that each got.

#15 결혼식 생성, QR 코드 생성 및 S3 이미지 저장
  build.gradle
  src/main/java/com/kestrel/weddingbookkeeper/api/member/dao/MemberDao.java
  src/main/java/com/kestrel/weddingbookkeeper/api/member/exception/MemberNotFoundException.java
  src/main/java/com/kestrel/weddingbookkeeper/api/member/service/MemberService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/member/service/impl/MemberServiceImpl.java
  src/main/java/com/kestrel/weddingbookkeeper/api/member/vo/Gender.java
  src/main/java/com/kestrel/weddingbookkeeper/api/member/vo/Member.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/controller/WeddingController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dao/WeddingDao.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dto/WeddingInfoRequestDto.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dto/WeddingInsertDto.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dto/request/WeddingInfoRequest.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/exception/QRCodeGenerationException.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/exception/WeddingInfoNotSavedException.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/facade/WeddingFacade.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/facade/impl/WeddingFacadeImpl.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/WeddingService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/impl/QrService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/impl/WeddingServiceImpl.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/util/ValidationCodeGenerator.java
  src/main/java/com/kestrel/weddingbookkeeper/common/configuration/JasyptConfiguration.java
  src/main/java/com/kestrel/weddingbookkeeper/common/configuration/MyBatisConfiguration.java
  src/main/java/com/kestrel/weddingbookkeeper/common/util/DateUtils.java
  src/main/java/com/kestrel/weddingbookkeeper/external/storage/configuration/AwsS3Configuration.java
  src/main/java/com/kestrel/weddingbookkeeper/external/storage/exception/AwsS3Exception.java
  src/main/java/com/kestrel/weddingbookkeeper/external/storage/service/FileService.java
  src/main/java/com/kestrel/weddingbookkeeper/external/storage/service/impl/AwsS3FileService.java
  src/main/resources/application.yml
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/mapper/WeddingMapper.xml
Labels: enhancement

#16 결혼식 내부 로직 변경
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/controller/WeddingController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dao/WeddingDao.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dto/WeddingInsertDto.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dto/WeddingUpdateDto.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/exception/WeddingInfoNotUpdateException.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/facade/WeddingFacade.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/facade/impl/WeddingFacadeImpl.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/WeddingService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/impl/QrService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/impl/WeddingServiceImpl.java
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/mapper/WeddingMapper.xml
Labels: refactor

#18 마이페이지 결혼식 정보 가져오기 및 배우자 연결하기
  src/main/java/com/kestrel/weddingbookkeeper/api/member/vo/Member.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/controller/WeddingController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dao/WeddingDao.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dto/PartnerDto.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dto/request/PartnerCodeRequest.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dto/response/WeddingInfoResponse.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/exception/InvalidGenderException.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/WeddingService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/impl/WeddingServiceImpl.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/vo/Wedding.java
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/mapper/WeddingMapper.xml
Labels: enhancement

#22 마이페이지 결혼식 정보 수정
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/controller/WeddingController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dao/WeddingDao.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dto/WeddingInfoRequestDto.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dto/WeddingInfoUpdateDto.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dto/request/WeddingUpdateInfomationRequest.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/exception/ValidationCodeMisMatchException.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/exception/WeddingInfomationNotUpdateException.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/facade/impl/WeddingFacadeImpl.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/WeddingService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/impl/WeddingServiceImpl.java
  src/main/resources/mapper/WeddingMapper.xml
Labels: enhancement

#23 결혼식 QR 조회
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/controller/WeddingController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dao/WeddingDao.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dto/response/WeddingQrResponse.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/WeddingService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/impl/WeddingServiceImpl.java
  src/main/resources/mapper/WeddingMapper.xml
Labels: enhancement

#26 축의금 납부 목록 조회 기능
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/controller/WeddingController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dao/MemberWeddingDao.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/WeddingService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/impl/WeddingServiceImpl.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/vo/MemberWedding.java
  src/main/resources/application.yml
  src/main/resources/mapper/MemberWeddingMapper.xml
Labels: enhancement

#24 관리자 코드 조회
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/controller/WeddingController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dao/WeddingDao.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dto/response/WeddingManagerCodeResponse.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/WeddingService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/impl/WeddingServiceImpl.java
  src/main/resources/mapper/WeddingMapper.xml
Labels: enhancement

#27 merge하면서 생긴 버그 해결
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/controller/WeddingController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/WeddingService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/impl/WeddingServiceImpl.java
  src/main/resources/mapper/WeddingMapper.xml
Labels: bug
