Repository festal-kestrel/wedding-book-keeper-be, pull requests merged in 2023-07, with the labels that each got.

#17 카카오 소셜 로그인 구현
  build.gradle
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/controller/AuthController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/controller/OauthController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/dao/JwtTokenDao.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/dto/KakaoResponseDto.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/exception/JwtTokenNotSavedException.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/service/OauthService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/service/impl/OauthServiceImpl.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/utils/AuthToken.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/utils/AuthTokenProvider.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/utils/JwtAuthenticationFilter.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/utils/JwtHeaderUtil.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/utils/KakaoUtil.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/utils/WeddingMember.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/vo/JwtToken.java
  src/main/java/com/kestrel/weddingbookkeeper/api/member/controller/MemberController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/member/dao/MemberDao.java
  src/main/java/com/kestrel/weddingbookkeeper/api/member/exception/MemberNotRegisteredException.java
  src/main/java/com/kestrel/weddingbookkeeper/api/member/service/MemberService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/member/service/impl/MemberServiceImpl.java
  src/main/java/com/kestrel/weddingbookkeeper/api/member/vo/Member.java
  src/main/java/com/kestrel/weddingbookkeeper/common/configuration/SecurityConfig.java
  src/main/resources/application.yml
  src/main/resources/mapper/JwtTokenMapper.xml
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/mapper/WeddingMapper.xml
Labels: enhancement

#29 신랑/신부, 관리자 화면에서의 하객 리스트 조회
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/controller/WeddingController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dao/MemberWeddingDao.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/WeddingService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/impl/WeddingServiceImpl.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/vo/MemberWedding.java
  src/main/resources/mapper/MemberWeddingMapper.xml
Labels: enhancement

#31 Redis 세팅
  build.gradle
  src/main/java/com/kestrel/weddingbookkeeper/common/util/EmbeddedRedisConfiguration.java
  src/main/java/com/kestrel/weddingbookkeeper/common/util/RedisConfiguration.java
  src/main/resources/application.yml
Labels: enhancement

#35 mapper 메서드 추가
  src/main/resources/mapper/MemberMapper.xml
Labels: bug

#36 인증코드 조회 및 인증 API 구현
  src/main/java/com/kestrel/weddingbookkeeper/WeddingBookKeeperApplication.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/controller/AuthController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/dao/VerificationCodeRepository.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/dto/request/VerificationCodeRequest.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/dto/response/VerificationCodeResponse.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/exception/VerificationCodeNotFoundException.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/facade/AuthFacade.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/facade/impl/AuthFacadeImpl.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/service/AuthService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/service/impl/AuthServiceImpl.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/vo/VerificationCode.java
  src/main/java/com/kestrel/weddingbookkeeper/api/member/dao/MemberDao.java
  src/main/java/com/kestrel/weddingbookkeeper/api/member/exception/GenderMatchException.java
  src/main/java/com/kestrel/weddingbookkeeper/api/member/exception/InvalidRoleNameException.java
  src/main/java/com/kestrel/weddingbookkeeper/api/member/exception/UnsupportedGenderTypeException.java
  src/main/java/com/kestrel/weddingbookkeeper/api/member/service/MemberService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/member/service/impl/MemberServiceImpl.java
  src/main/java/com/kestrel/weddingbookkeeper/api/member/vo/Member.java
  src/main/java/com/kestrel/weddingbookkeeper/api/member/vo/Role.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/controller/WeddingController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dao/WeddingDao.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dto/WeddingInsertDto.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/exception/WeddingNotFoundException.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/factory/WeddingFactory.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/factory/impl/BrideWeddingFactory.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/factory/impl/GroomWeddingFactory.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/WeddingService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/impl/WeddingServiceImpl.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/util/VerificationCodeGenerator.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/vo/Wedding.java
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/mapper/MemberWeddingMapper.xml
  src/main/resources/mapper/WeddingMapper.xml
Labels: enhancement

#37 축의금 납부 내역 API 응답 포맷 변경
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/controller/WeddingController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dao/MemberWeddingDao.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dto/response/DonationReceiptResponse.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dto/response/DonationReceiptsResponse.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dto/response/GuestDonationReceiptResponse.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dto/response/GuestDonationReceiptsResponse.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/facade/impl/WeddingFacadeImpl.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/WeddingService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/impl/WeddingServiceImpl.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/vo/MemberWedding.java
  src/main/resources/mapper/MemberWeddingMapper.xml
  src/main/resources/mapper/WeddingMapper.xml
Labels: enhancement

#38 클래스명 수정
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/controller/WeddingController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dao/WeddingDao.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dto/WeddingInfoUpdateDto.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dto/request/WeddingUpdateInformationRequest.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/exception/WeddingInformationUpdateException.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/WeddingService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/impl/WeddingServiceImpl.java
  src/main/resources/mapper/WeddingMapper.xml
Labels: enhancement

#39 Swagger ApiResponse 추가 및 클래스, 패키지명 통일
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/controller/AuthController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/controller/OauthController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/service/impl/AuthServiceImpl.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/controller/WeddingController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dto/WeddingInsertDto.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/utils/VerificationCodeGenerator.java
  src/main/java/com/kestrel/weddingbookkeeper/common/configuration/EmbeddedRedisConfiguration.java
  src/main/java/com/kestrel/weddingbookkeeper/common/configuration/RedisConfiguration.java
  src/main/java/com/kestrel/weddingbookkeeper/common/configuration/SecurityConfiguration.java
  src/main/java/com/kestrel/weddingbookkeeper/common/configuration/SwaggerConfiguration.java
  src/main/java/com/kestrel/weddingbookkeeper/common/utils/DateUtils.java
Labels: enhancement

#43 회원 정보 조회 API 구현
  src/main/java/com/kestrel/weddingbookkeeper/api/member/controller/MemberController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/member/dto/response/MemberInformationResponse.java
  src/main/java/com/kestrel/weddingbookkeeper/api/member/service/MemberService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/member/service/impl/MemberServiceImpl.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/controller/WeddingController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dto/response/WeddingIdResponse.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/facade/WeddingFacade.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/facade/impl/WeddingFacadeImpl.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/factory/WeddingFactory.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/factory/impl/BrideWeddingFactory.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/factory/impl/GroomWeddingFactory.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/WeddingService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/impl/WeddingServiceImpl.java
Labels: enhancement

#44 fix: 클래스명 수정
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/controller/WeddingController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/WeddingService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/impl/WeddingServiceImpl.java
  src/main/resources/mapper/WeddingMapper.xml
Labels: bug

#45 fix : 하객QR입장 api명세에 맞게 수정
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/controller/WeddingController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dao/MemberWeddingDao.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dto/MemberWeddingDto.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dto/MemberWeddingSaveDto.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/WeddingService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/impl/WeddingServiceImpl.java
  src/main/resources/mapper/MemberWeddingMapper.xml
Labels: enhancement

#46 feat : has-paid 변경 api 구현
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/controller/WeddingController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dao/MemberWeddingDao.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/WeddingService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/impl/WeddingServiceImpl.java
  src/main/resources/mapper/MemberWeddingMapper.xml
Labels: enhancement

#50 id 자료형 변경
  src/main/java/com/kestrel/weddingbookkeeper/api/admin/controller/AdminController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/controller/AuthController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/controller/OauthController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/dao/VerificationCodeRepository.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/facade/AuthFacade.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/facade/impl/AuthFacadeImpl.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/service/AuthService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/service/OauthService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/service/impl/AuthServiceImpl.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/service/impl/OauthServiceImpl.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/utils/AuthToken.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/utils/AuthTokenProvider.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/vo/VerificationCode.java
  src/main/java/com/kestrel/weddingbookkeeper/api/member/controller/MemberController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/member/dao/MemberDao.java
  src/main/java/com/kestrel/weddingbookkeeper/api/member/dto/response/MemberInformationResponse.java
  src/main/java/com/kestrel/weddingbookkeeper/api/member/service/MemberService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/member/service/impl/MemberServiceImpl.java
  src/main/java/com/kestrel/weddingbookkeeper/api/member/vo/Member.java
  src/main/java/com/kestrel/weddingbookkeeper/api/notification/service/NotificationService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/controller/WeddingController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dao/MemberWeddingDao.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dao/WeddingDao.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dto/MemberWeddingDto.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dto/MemberWeddingSaveDto.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dto/PartnerDto.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dto/WeddingInsertDto.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dto/WeddingUpdateDto.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dto/response/WeddingIdResponse.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/facade/WeddingFacade.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/facade/impl/WeddingFacadeImpl.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/WeddingService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/impl/QrService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/impl/WeddingServiceImpl.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/vo/Wedding.java
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/mapper/MemberWeddingMapper.xml
Labels: enhancement

#51 AuthenticationPrinciple 적용
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/controller/AuthController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/controller/OauthController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/member/controller/MemberController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/notification/service/NotificationService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/controller/WeddingController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/vo/MemberWedding.java
  src/main/java/com/kestrel/weddingbookkeeper/common/configuration/SecurityConfiguration.java
Labels: enhancement

#54 guestId 필드 추가
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/controller/WeddingController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dto/response/GuestDonationReceiptResponse.java
Labels: enhancement

#57 배우자 인증코드 인증 response 수정
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/controller/AuthController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/dto/response/VerifyPartnerVerificationCodeResponse.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/facade/AuthFacade.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/facade/impl/AuthFacadeImpl.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/factory/WeddingFactory.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/factory/impl/BrideWeddingFactory.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/factory/impl/GroomWeddingFactory.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/WeddingService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/impl/WeddingServiceImpl.java
Labels: enhancement

#61 메인페이지 리스트 시간 순으로 정렬
  src/main/resources/mapper/MemberWeddingMapper.xml
Labels: enhancement

#62 잘못된 import문 삭제
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/controller/WeddingController.java
Labels: bug

#63 MemberWeddingMapper 정렬 수정
  src/main/resources/mapper/MemberWeddingMapper.xml
Labels: bug

#64 security web ignore 변경
  src/main/java/com/kestrel/weddingbookkeeper/common/configuration/SecurityConfiguration.java
Labels: enhancement

#65 결혼식 정보 생성 내부 로직 변경
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dao/WeddingDao.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dto/WeddingBrideInsertDto.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/dto/WeddingGroomInsertDto.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/factory/WeddingFactory.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/factory/impl/BrideWeddingFactory.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/factory/impl/GroomWeddingFactory.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/impl/WeddingServiceImpl.java
  src/main/resources/mapper/WeddingMapper.xml
Labels: refactor

#67 codeowners 제거
  .github/CODEOWNERS
Labels: documentation

#68 인증코드 검증 내부 로직 변경
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/controller/AuthController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/dao/VerificationCodeRepository.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/dto/ManagerVerificationCodeRequest.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/facade/AuthFacade.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/service/AuthService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/service/impl/AuthServiceImpl.java
  src/main/java/com/kestrel/weddingbookkeeper/api/auth/vo/PartnerVerificationCode.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/controller/WeddingController.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/WeddingService.java
  src/main/java/com/kestrel/weddingbookkeeper/api/wedding/service/impl/WeddingServiceImpl.java
Labels: refactor
